### ISSUE TITLE
Make all event interfaces implement another interface?

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonar#155]
So far all interface events have the `resource` property and we are required to have it because of [this](https://github.com/MicrosoftEdge/Sonar/blob/44688ca2a18384b85b0325a0067ef2ad136dc6f1/src/lib/sonar.ts#L86).

I just had a problem where I created a new event and forgot to add that property so I'm thinking that we should do something like:

```typescript
export interface ISonarEvent {
  resource: string;
// any other common things in here
}

export interface IRandomEvent implements ISonarEvent {
// stuff here
}
```

That way if we need to change some common stuff is easier and forgetting them more complicated.

@alrra, @sarvaje thoughts?

**Comment by molant** [comment]
@sarvaje I think you are taking care of this in #76 so I'm assigning it to you.

**Comment by sarvaje** [comment]
This is fixed in https://github.com/sonarwhal/sonar/commit/65528ed3bbb368ca20bb46c3d3f8a08ae35a2234
