### ISSUE TITLE
Return the right value for `rawResponse` in CDP

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonar#164]
Right now ` rawContent`  returns a ` Buffer`  with the right size but no content, and `rawResponse` doesn't return anything.
* [x] `rawContent`
* [x] `rawResponse`

**Comment by molant** [comment]
@paulirish, @ebidel, do you know if there is a way to get the real bytes of a response? I can get the decoded ones but nothing else :(
If not, we might have to rely on `request` and use the same headers than the original request.

**Comment by paulirish** [comment]
@molant replied on https://github.com/ChromeDevTools/devtools-protocol/issues/12 -- It seems like doing a followup request from node is the only workaround for this right now.

**Comment by alrra** [comment]
@paulirish Thanks for looking into it! 💜

**Comment by molant** [comment]
If we have to use `request` to do the reply we need to take into account the `headers` and `cookies` used in originally.

**Comment by molant** [comment]
Also, I think that we should change the type of `rawResponse` from `Buffer` to `Promise<Buffer>`. The reason is that not all the rule configurations require this value and we will be making extra requests that are not needed and thus wasting time and bandwidth. We could potentially do the same for `rawBody`, I've seen it takes sometimes a bit to get the data too.

**Comment by molant** [comment]
After syncing with @alrra my current plan for this is to:

* make `rawResponse` and `rawBody` methods that return a `Promise<Buffer>`. This way we are not making things when we don't need.
* user `requester` to get the `rawResponse` in `remote-debugging-connector`. Looks like this is the only way to get the response. We will use the same headers as the original request
