### ISSUE TITLE
Edge connector

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonar#170]
We need to start working on the Edge collector.
* [ ] Launch and close the browser using the regular [edge diagnostics adapter](https://github.com/Microsoft/edge-diagnostics-adapter).
* [ ] Integrate with the work being done in this fork of the [edge diagnostics adapter](https://github.com/PlainConcepts/edge-diagnostics-adapter). Maybe as a submodule for now? Need to figure out how to compile it
* [ ] ??

Ideally we should use most of CDP except the launcher and maybe a couple other things. We could:
1. Make a `super` collector and inherit for chrome and/or edge (or have mixins) and then have several collectors.
1. Just have one collector and via the configurator we change what needs to be used as launcher or not.

```js
"collector": {
        "name": "cdp",
        "options": {
            "browser": "edge",
            "waitFor": 100
        }
    },
```

The problem with 2 is that enabling testing in all collectors will be a bit more complex (right now we are just passing the names of the `collector`s).

**Comment by molant** [comment]
@sarvaje did you pushed all the changes to https://github.com/sonarwhal/connector-edge15 ? If so I think we can close this and use https://github.com/sonarwhal/connector-edge15/issues/3 to track the final status.

**Comment by sarvaje** [comment]
@molant yep, all changes are in https://github.com/sonarwhal/connector-edge15. And also all the changes that sonar needs are merged, so we can close this task.
