### ISSUE TITLE
Add rule(s) to check the usage of the `Strict-Transport-Security` HTTP header

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonar#23]
- [x] Check if the header `Strict-Transport-Security` is sent for resources served over HTTPS.
- [x] Check if the `max-age` value  is small (less than 10886400 seconds should be an error, no configuration possible).

---

Also inform users about https://hstspreload.org/? However, make it clear that:

  * the preload list cannot easily be undone (domains can be removed, but it takes months for a change to reach users, basically until those users upgrade to a new version of the browser)
  * they should only do this if they are sure that they can support HTTPS for their entire site and all its `subdomains` in the long run.

---

See also:

* https://tools.ietf.org/html/rfc6797
* https://www.owasp.org/index.php/HTTP_Strict_Transport_Security

**Comment by qzhou1607** [comment]
@molant @alrra It seems that we can only serve over HTTP in localhost. To do the tests in this rule, is there an easier way than adding an additional HTTPS server?

**Comment by alrra** [comment]
> To do the tests in this rule, is there an easier way than adding an additional HTTPS server?

Don't think so (+ we will need to add support for HTTPS for testing anyway). Can you open an issue for that? Thanks!

> adding an additional HTTPS server?

We can use Express (we just need to generate some self-signed certificates and configure it to use them).
