### ISSUE TITLE
Add rule to check for `Secure` and `HttpOnly` cookies

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonar#24]
- [ ]  Check if the `Set-Cookie` header is sent with the `Secure` and `HttpOnly` values if the page is served over HTTPS.

---

See also:

* https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Secure_and_HttpOnly_cookies

**Comment by qzhou1607** [comment]
A few more checks:
* [ ] In the same set-cookie-string, two attributes shouldn't have the same name.
* [ ] The name-value-pair string needs to have `=`, otherwise it will be ignored entirely.
