### ISSUE TITLE
Improve contributors page

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonar#279]
Maybe use something like https://github.com/kentcdodds/all-contributors

Ref: https://github.com/MicrosoftEdge/Sonar/pull/257#discussion_r122166184

**Comment by ststimac** [comment]
Do we want to add the type of contributions people have made? I ask because I added them (the emojis) and they link to the commit history specifically under this repo and not sonarwhal.com.

**Comment by molant** [comment]
I think that having the type of contribution is nice. Maybe keeping track of the types of commits is a bit too much and we should just use the emojis without links?

**Comment by molant** [comment]
@ststimac is there anything pending in this issue?

**Comment by ststimac** [comment]
@molant not that I'm aware. The PR for this was closed in June and I don't recall any other requests for updates.
