### ISSUE TITLE
[Proposal] Improve rules configuration (include/exclude)

### ISSUE THREAD

**Issue by patrick-steele-idem** [sonarwhal/sonar#283]
Configuring rules is going to be one of the most common thing and I think there is room for improvement. It appears that the configuration structure was inspired by ESLint, but I feel like the following would be more intuitive:

```js
{
    "rules": [
        "rule1",        // Default to "error"
        "rule2:warn",   // Switch to warn
        "rule3:off",    // Quickly disable a rule
        ["rule4", {
            exclude: /.*\.foo\.com/.*/
        }],
        ["rule5", {
            include: [/.*\.domain1\.com/.*/],
            exclude: [/.*\.foo\.com/.*/]
        }],
        ["rule6", {
            include: ['*.domain1.com/**'] // Simple glob
        }],
        { // Additional rules for a specific domain
          include: ['*.foo.com/**'],
          rules: [
            'rule7',
            'rule8'
          ]
        }
    ],
    include: [ // Only run rules for the following URLs
      '*.ebay.com'
    ],
    exclude: [ // Don't run rules for any of the following URLs
      'tracking.ebay.com'
    ]
}
```

As shown above, each rule should support an include and exclude option. Value could either a be string (treated as a glob), a JS regular expression or an Array of either of those. The code above also shows how a global exclude/include could be supported.

**Comment by austinkelleher** [comment]
@molant I can take this one

**Comment by molant** [comment]
Go for it, I think you can assign yourself to this task.
I'm refactoring how we are loading the rules, collectors, etc. And I'm changing where the validation is done (`sonar.ts` instead of `cli.ts`) . I don't think this is going to impact you but just FYI.
Hopefully I'll have the PR done by the end of the day for review :)

**Comment by austinkelleher** [comment]
@molant Okay thanks for the heads up. I cannot assign myself. I assume this has to do with the fact that the repo was moved to its own org.

**Comment by molant** [comment]
@austinkelleher you should be now a contributor :)

**Comment by austinkelleher** [comment]
Thanks!
