### ISSUE TITLE
[Proposal] Allow README.md for rules

### ISSUE THREAD

**Issue by patrick-steele-idem** [sonarwhal/sonar#285]
I think it would be very beneficial and more user friendly if every rule had `README.md` with detailed information about the rule. To support this, I propose switching to the following directory structure for each rule:

```
rules/my-awesome-rule/
  index.ts     # Using `index.ts` instead of `my-awesome-rule.ts`
                    # is More DRY (makes renaming a rule easier)
  README.md    # Documentation/More info about the rule
```

it would be nice if maybe a link (file path or URL?) to the rule's README.md could be included in the output on the CLI (or shown in an [HTML report](https://github.com/MicrosoftEdge/Sonar/issues/284))

**Comment by alrra** [comment]
> > but I think of rule+docs as a single module/unit that is best kept close together. 
>
> We started down that path and finally decided to move everything under /docs/ for consistency 

At that time we had the tests separate from the rules, but the docs with the rules. Only the rules had the docs with them, nothing else, so the decision was to either have everything together (rule + docs + tests), or group everything (tests, docs, rules). We went with the the latter.

**Comment by molant** [comment]
I think for now we are going to keep the current structure and keep all the documentation together. We can always reopen this issue if people start asking about it.
