### ISSUE TITLE
[Proposal] Move away from the term "Collectors" for end users?

### ISSUE THREAD

**Issue by patrick-steele-idem** [sonarwhal/sonar#286]
I understand why you went with the name "Collectors", but I feel like "Browser Engines" would be more relatable to by end users. At first glance, I was confused by the usage of "Collectors". Maybe keep "collector" as more of an implementation detail? Maybe use "connector" instead ("Connectors are used to connect Sonar with browser engines")?

**Comment by alrra** [comment]
> I'm ok switching to `connector`

Same here.

---

@patrick-steele-idem Wanna open a PR?

**Comment by patrick-steele-idem** [comment]
Possibly, but I'm also trying to make some progress with [another open source project by Microsoft](https://github.com/Microsoft/ghcrawler/pull/103) so unfortunately I don't think I would be able to get to this right away. Also, what are the options on the table since `browser engines` may also be controversial?

**Comment by molant** [comment]
Connector is the only option at the moment. I've looked in thesaurus.com a bit but I don't see any other word that I like.

**Comment by kborchers** [comment]
So just thinking about the parts of an [active sonar system](https://en.wikipedia.org/wiki/Sonar#Active_sonar), I like [transducer](https://en.wikipedia.org/wiki/Transducer). 🛥

**Comment by patrick-steele-idem** [comment]
I don't think `Connector` is much better. From a user perspective, they are just linting a webpage in a particular browser (or browser-like environment).

**Comment by patrick-steele-idem** [comment]
`transducer` is cool, but might be a little too abstract 😀

**Comment by kborchers** [comment]
I think `transponder` is more accurate in terms of functionality and is maybe a bit more familiar word for folks as opposed to `transducer`

**Comment by kborchers** [comment]
I guess not a lot of love for `transponder` either?

**Comment by patrick-steele-idem** [comment]
`transponder` is not bad and matches the project name, but I'm not sure it is a good idea to leak the project branding into the code. I still think that from a user perspective they are just choosing to do linting of a web page using a `browser` engine (the interface to communicate with the browser and how data is collected should not matter and should not be the focus)

**Comment by kborchers** [comment]
These are good points. I honestly don't think collector is bad so was just trying to come up with creative suggestions but your points make sense and I agree.

**Comment by cfjedimaster** [comment]
As a *very* new user who was thrown by this term, I'd also vote for connector.

**Comment by alrra** [comment]
We'll go with `connector` for the time being.
