### ISSUE TITLE
[Proposal] Avoid encoding JavaScript regular expressions in strings

### ISSUE THREAD

**Issue by patrick-steele-idem** [sonarwhal/sonar#287]
Encoding regular expressions as JavaScript strings is kind of awful because of the escaping rules. Maybe default to using glob patterns instead (perhaps use [minimatch](https://github.com/isaacs/minimatch))?

Instead of the following:

```json
"ignoredUrls": {
    ".*\\.domain1\\.com/.*": ["*"],
    "www.domain2.net": ["disallowed-headers"]
}
```

I propose the following:

```json
"ignoredUrls": {
    "*.domain1.com/**": ["*"],
    "www.domain2.net": ["disallowed-headers"]
}
```

In cases where `.sonarrc.js` is used, the developer could directly provide a JavaScript regular expression (assuming the regular expression is not a key in an object...as is the case above).

**Comment by molant** [comment]
Closing this issues as [we decided](https://github.com/sonarwhal/sonar/pull/292#issuecomment-312267954) to focus on #343 instead.
