### ISSUE TITLE
Don't fail builds because of broken links

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonar#288]
During the build process we check that the links are up and running. While this helps us make sure our references still exist it can cause some problems when we want to ship something and I don't think that a server that is down should block us. Maybe we could a have a scheduled task that opens an issue if the link fails or something similar?

For example, right now we are blocked because https://html5sec.org is not working.

**Comment by alrra** [comment]
> Maybe we could a have a scheduled task that opens an issue if the link fails or something similar?

Yes. We can set up a [cron job](https://docs.travis-ci.com/user/cron-jobs/) that runes for example, every week, and make it open a issues for broken links.

**Comment by alrra** [comment]
I'll look into it, in the next few days.

**Comment by alrra** [comment]
I've added a [cron job](https://docs.travis-ci.com/user/cron-jobs/) that will execute daily (based on how it goes, we may change it to weekly), and if broken links are found, our [machine user](https://github.com/NellieTheNarwhal) will open an issue such as https://github.com/sonarwhal/sonar/issues/336.

**Comment by molant** [comment]
Build 184.1 failed because of a broken link so I'm reopening this.

**Comment by alrra** [comment]
> Build 184.1 failed because of a broken link so I'm reopening this.

Build [184.1](https://travis-ci.org/sonarwhal/sonar/jobs/249880967) is a cron job, it is supposed to fail if there are broken links.

> We should also remove the sites in the whitelist.

https://example2.com/ doesn't exists, so it should be in the whitelist.

**Comment by molant** [comment]
The problem is that it marka the master branch as failing and it doesn't look great.

Re the white list I thought there were more domains than example2.com (I added a bunch before).

**Comment by molant** [comment]
After talking with @alrra this is my position:
> I just want to know somehow that some links are failing. Ideally it should be via github issues but I don't think a problem with a link should fail a build. We have to know when a link is broken and look into it, and I think that opening an issue should be enough. Most of the links we have are external and just fail temporarily so failing a build because of that is too drastic IMO.

**Comment by alrra** [comment]
> The problem is that it marka the master branch as failing and it doesn't look great.

That was intentional. 

> I just want to know somehow that some links are failing. Ideally it should be via github issues but I don't think a problem with a link should fail a build. We have to know when a link is broken and look into it, and I think that opening an issue should be enough. Most of the links we have are external and just fail temporarily so failing a build because of that is too drastic IMO.

:+1:

> Re the white list I thought there were more domains than example2.com (I added a bunch before).

I've progressively removed them (e.g.: see https://github.com/sonarwhal/sonar/commit/b64c98ac3419b207a6a2670679b5a74c56675431) to the point of only having the ones that are actually needed.
