### ISSUE TITLE
Build fails on Mac 10.11.6 (El Capitan) 

### ISSUE THREAD

**Issue by wmelton** [sonarwhal/sonar#299]
`USER_1:~ USER_1_MP: npm install -g @sonarwhal/sonar
/usr/local/bin/sonar -> /usr/local/lib/node_modules/@sonarwhal/sonar/dist/src/bin/sonar.js

> canvas-prebuilt@1.6.0 install /usr/local/lib/node_modules/@sonarwhal/sonar/node_modules/canvas-prebuilt
> node-pre-gyp install

[canvas-prebuilt] Success: "/usr/local/lib/node_modules/@sonarwhal/sonar/node_modules/canvas-prebuilt/canvas/build/Release/canvas-prebuilt.node" is installed via remote
/usr/local/lib
└─┬ @sonarwhal/sonar@0.0.2
  ├── axe-core@2.3.1
  ├─┬ browserslist@2.1.5
  │ ├── caniuse-lite@1.0.30000693
  │ └── electron-to-chromium@1.3.14
  ├─┬ canvas-prebuilt@1.6.0
  │ └─┬ node-pre-gyp@0.6.36
  │   ├─┬ nopt@4.0.1
  │   │ ├── abbrev@1.1.0
  │   │ └── osenv@0.1.4
  │   ├─┬ npmlog@4.1.0
  │   │ ├─┬ are-we-there-yet@1.1.4
  │   │ │ └── delegates@1.0.0
  │   │ ├── console-control-strings@1.1.0
  │   │ ├─┬ gauge@2.7.4
  │   │ │ ├── aproba@1.1.2
  │   │ │ ├── has-unicode@2.0.1
  │   │ │ └── wide-align@1.1.2
  │   │ └── set-blocking@2.0.0
  │   ├─┬ rc@1.2.1
  │   │ ├── deep-extend@0.4.2
  │   │ ├── ini@1.3.4
  │   │ └── minimist@1.2.0
  │   ├── rimraf@2.6.1
  │   ├── semver@5.3.0
  │   ├─┬ tar@2.2.1
  │   │ ├── block-stream@0.0.9
  │   │ └── fstream@1.0.11
  │   └─┬ tar-pack@3.4.0
  │     ├── fstream-ignore@1.0.5
  │     └── uid-number@0.0.6
  ├─┬ chalk@1.1.3
  │ ├── ansi-styles@2.2.1
  │ ├── escape-string-regexp@1.0.5
  │ ├─┬ has-ansi@2.0.0
  │ │ └── ansi-regex@2.1.1
  │ ├── strip-ansi@3.0.1
  │ └── supports-color@2.0.0
  ├─┬ chrome-remote-interface@0.23.2
  │ ├── commander@2.1.0
  │ └─┬ ws@2.0.3
  │   └── ultron@1.1.0
  ├── content-type@1.0.2
  ├─┬ debug@2.6.8
  │ └── ms@2.0.0
  ├─┬ eslint@3.19.0
  │ ├─┬ babel-code-frame@6.22.0
  │ │ └── js-tokens@3.0.1
  │ ├─┬ concat-stream@1.6.0
  │ │ ├── inherits@2.0.3
  │ │ ├─┬ readable-stream@2.3.2
  │ │ │ ├── core-util-is@1.0.2
  │ │ │ ├── process-nextick-args@1.0.7
  │ │ │ ├─┬ string_decoder@1.0.2
  │ │ │ │ └── safe-buffer@5.0.1
  │ │ │ └── util-deprecate@1.0.2
  │ │ └── typedarray@0.0.6
  │ ├─┬ doctrine@2.0.0
  │ │ └── isarray@1.0.0
  │ ├─┬ escope@3.6.0
  │ │ ├─┬ es6-map@0.1.5
  │ │ │ ├── d@1.0.0
  │ │ │ ├── es5-ext@0.10.23
  │ │ │ ├── es6-iterator@2.0.1
  │ │ │ ├── es6-set@0.1.5
  │ │ │ ├── es6-symbol@3.1.1
  │ │ │ └── event-emitter@0.3.5
  │ │ ├── es6-weak-map@2.0.2
  │ │ └── esrecurse@4.2.0
  │ ├─┬ espree@3.4.3
  │ │ ├── acorn@5.0.3
  │ │ └─┬ acorn-jsx@3.0.1
  │ │   └── acorn@3.3.0
  │ ├── esquery@1.0.0
  │ ├── estraverse@4.2.0
  │ ├── esutils@2.0.2
  │ ├─┬ file-entry-cache@2.0.0
  │ │ └─┬ flat-cache@1.2.2
  │ │   ├── circular-json@0.3.1
  │ │   ├─┬ del@2.2.2
  │ │   │ ├─┬ globby@5.0.0
  │ │   │ │ └── arrify@1.0.1
  │ │   │ ├── is-path-cwd@1.0.0
  │ │   │ └─┬ is-path-in-cwd@1.0.0
  │ │   │   └── is-path-inside@1.0.0
  │ │   ├── graceful-fs@4.1.11
  │ │   └── write@0.2.1
  │ ├─┬ glob@7.1.2
  │ │ ├── fs.realpath@1.0.0
  │ │ ├─┬ inflight@1.0.6
  │ │ │ └── wrappy@1.0.2
  │ │ ├─┬ minimatch@3.0.4
  │ │ │ └─┬ brace-expansion@1.1.8
  │ │ │   ├── balanced-match@1.0.0
  │ │ │   └── concat-map@0.0.1
  │ │ ├── once@1.4.0
  │ │ └── path-is-absolute@1.0.1
  │ ├── globals@9.18.0
  │ ├── ignore@3.3.3
  │ ├── imurmurhash@0.1.4
  │ ├─┬ inquirer@0.12.0
  │ │ ├── ansi-escapes@1.4.0
  │ │ ├─┬ cli-cursor@1.0.2
  │ │ │ └─┬ restore-cursor@1.0.1
  │ │ │   ├── exit-hook@1.1.1
  │ │ │   └── onetime@1.1.0
  │ │ ├── figures@1.7.0
  │ │ ├─┬ readline2@1.0.1
  │ │ │ ├── code-point-at@1.1.0
  │ │ │ ├─┬ is-fullwidth-code-point@1.0.0
  │ │ │ │ └── number-is-nan@1.0.1
  │ │ │ └── mute-stream@0.0.5
  │ │ ├── run-async@0.1.0
  │ │ ├── rx-lite@3.1.2
  │ │ └── string-width@1.0.2
  │ ├─┬ js-yaml@3.8.4
  │ │ ├─┬ argparse@1.0.9
  │ │ │ └── sprintf-js@1.0.3
  │ │ └── esprima@3.1.3
  │ ├── levn@0.3.0
  │ ├── natural-compare@1.4.0
  │ ├── pluralize@1.2.1
  │ ├── progress@1.1.8
  │ └─┬ table@3.8.3
  │   ├─┬ ajv@4.11.8
  │   │ └── co@4.6.0
  │   ├── ajv-keywords@1.5.1
  │   ├── slice-ansi@0.0.4
  │   └─┬ string-width@2.0.0
  │     └── is-fullwidth-code-point@2.0.0
  ├── eventemitter2@4.1.0
  ├── file-type@5.2.0
  ├── file-url@2.0.2
  ├─┬ globby@6.1.0
  │ ├─┬ array-union@1.0.2
  │ │ └── array-uniq@1.0.3
  │ ├── object-assign@4.1.1
  │ ├── pify@2.3.0
  │ └─┬ pinkie-promise@2.0.1
  │   └── pinkie@2.0.4
  ├── iconv-lite@0.4.18
  ├─┬ inquirer@3.1.1
  │ ├── ansi-escapes@2.0.0
  │ ├─┬ cli-cursor@2.1.0
  │ │ └─┬ restore-cursor@2.0.0
  │ │   ├─┬ onetime@2.0.1
  │ │   │ └── mimic-fn@1.1.0
  │ │   └── signal-exit@3.0.2
  │ ├── cli-width@2.1.0
  │ ├─┬ external-editor@2.0.4
  │ │ ├── jschardet@1.4.2
  │ │ └─┬ tmp@0.0.31
  │ │   └── os-tmpdir@1.0.2
  │ ├── figures@2.0.0
  │ ├── mute-stream@0.0.7
  │ ├─┬ run-async@2.3.0
  │ │ └── is-promise@2.1.0
  │ ├── rx-lite@4.0.8
  │ ├── rx-lite-aggregates@4.0.8
  │ ├─┬ string-width@2.0.0
  │ │ └── is-fullwidth-code-point@2.0.0
  │ └── through@2.3.8
  ├─┬ is-ci@1.0.10
  │ └── ci-info@1.0.0
  ├─┬ is-my-json-valid@2.16.0
  │ ├── generate-function@2.0.0
  │ ├─┬ generate-object-property@1.2.0
  │ │ └── is-property@1.0.2
  │ ├── jsonpointer@4.0.1
  │ └── xtend@4.0.1
  ├─┬ is-resolvable@1.0.0
  │ └── tryit@1.0.3
  ├─┬ is-svg@2.1.0
  │ └── html-comment-regex@1.1.1
  ├─┬ jsdom@11.0.0
  │ ├── abab@1.0.3
  │ ├── acorn@4.0.13
  │ ├─┬ acorn-globals@3.1.0
  │ │ └── acorn@4.0.13
  │ ├── array-equal@1.0.0
  │ ├── content-type-parser@1.0.1
  │ ├── cssom@0.3.2
  │ ├── cssstyle@0.2.37
  │ ├─┬ escodegen@1.8.1
  │ │ ├── esprima@2.7.3
  │ │ ├── estraverse@1.9.3
  │ │ └─┬ source-map@0.2.0
  │ │   └── amdefine@1.0.1
  │ ├── html-encoding-sniffer@1.0.1
  │ ├── nwmatcher@1.4.1
  │ ├─┬ parse5@3.0.2
  │ │ └── @types/node@6.0.78
  │ ├── pn@1.0.0
  │ ├─┬ request-promise-native@1.0.4
  │ │ ├── request-promise-core@1.1.1
  │ │ └── stealthy-require@1.1.1
  │ ├── sax@1.2.2
  │ ├── symbol-tree@3.2.2
  │ ├─┬ tough-cookie@2.3.2
  │ │ └── punycode@1.4.1
  │ ├── webidl-conversions@4.0.1
  │ ├─┬ whatwg-encoding@1.0.1
  │ │ └── iconv-lite@0.4.13
  │ ├─┬ whatwg-url@4.8.0
  │ │ ├── tr46@0.0.3
  │ │ └── webidl-conversions@3.0.1
  │ └── xml-name-validator@2.0.1
  ├─┬ json-stable-stringify@1.0.1
  │ └── jsonify@0.0.0
  ├── lockfile@1.0.3
  ├── lodash@4.17.4
  ├── mime-db@1.28.0
  ├─┬ mkdirp@0.5.1
  │ └── minimist@0.0.8
  ├─┬ node-ssllabs@0.5.0
  │ ├── async@0.9.2
  │ └── underscore@1.8.3
  ├─┬ optionator@0.8.2
  │ ├── deep-is@0.1.3
  │ ├── fast-levenshtein@2.0.6
  │ ├── prelude-ls@1.1.2
  │ ├── type-check@0.3.2
  │ └── wordwrap@1.0.0
  ├─┬ ora@1.3.0
  │ ├─┬ cli-cursor@2.1.0
  │ │ └─┬ restore-cursor@2.0.0
  │ │   └── onetime@2.0.1
  │ ├── cli-spinners@1.0.0
  │ └── log-symbols@1.0.2
  ├── path-is-inside@1.0.2
  ├── pluralize@5.0.0
  ├─┬ request@2.81.0
  │ ├── aws-sign2@0.6.0
  │ ├── aws4@1.6.0
  │ ├── caseless@0.12.0
  │ ├─┬ combined-stream@1.0.5
  │ │ └── delayed-stream@1.0.0
  │ ├── extend@3.0.1
  │ ├── forever-agent@0.6.1
  │ ├─┬ form-data@2.1.4
  │ │ └── asynckit@0.4.0
  │ ├─┬ har-validator@4.2.1
  │ │ └── har-schema@1.0.5
  │ ├─┬ hawk@3.1.3
  │ │ ├── boom@2.10.1
  │ │ ├── cryptiles@2.0.5
  │ │ ├── hoek@2.16.3
  │ │ └── sntp@1.0.9
  │ ├─┬ http-signature@1.1.1
  │ │ ├── assert-plus@0.2.0
  │ │ ├─┬ jsprim@1.4.0
  │ │ │ ├── assert-plus@1.0.0
  │ │ │ ├── extsprintf@1.0.2
  │ │ │ ├── json-schema@0.2.3
  │ │ │ └── verror@1.3.6
  │ │ └─┬ sshpk@1.13.1
  │ │   ├── asn1@0.2.3
  │ │   ├── assert-plus@1.0.0
  │ │   ├── bcrypt-pbkdf@1.0.1
  │ │   ├─┬ dashdash@1.14.1
  │ │   │ └── assert-plus@1.0.0
  │ │   ├── ecc-jsbn@0.1.1
  │ │   ├─┬ getpass@0.1.7
  │ │   │ └── assert-plus@1.0.0
  │ │   ├── jsbn@0.1.1
  │ │   └── tweetnacl@0.14.5
  │ ├── is-typedarray@1.0.0
  │ ├── isstream@0.1.2
  │ ├── json-stringify-safe@5.0.1
  │ ├─┬ mime-types@2.1.15
  │ │ └── mime-db@1.27.0
  │ ├── oauth-sign@0.8.2
  │ ├── performance-now@0.2.0
  │ ├── qs@6.4.0
  │ ├── safe-buffer@5.1.1
  │ ├── stringstream@0.0.5
  │ ├── tunnel-agent@0.6.0
  │ └── uuid@3.1.0
  ├─┬ require-uncached@1.0.3
  │ ├─┬ caller-path@0.1.0
  │ │ └── callsites@0.2.0
  │ └── resolve-from@1.0.1
  ├── same-origin@0.1.1
  ├─┬ shelljs@0.7.8
  │ ├── interpret@1.0.3
  │ └─┬ rechoir@0.6.2
  │   └─┬ resolve@1.3.3
  │     └── path-parse@1.0.5
  ├── strip-bom@3.0.0
  ├── strip-json-comments@2.0.1
  ├── text-table@0.2.0
  ├─┬ user-home@2.0.0
  │ └── os-homedir@1.0.2
  └─┬ which@1.2.14
    └── isexe@2.0.0

USER_1:~ USER_1_MP$ sonar --init
/usr/local/lib/node_modules/@sonarwhal/sonar/dist/src/bin/sonar.js:27
const run = async () => {
                  ^

SyntaxError: Unexpected token (
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:429:10)
    at startup (node.js:139:18)
    at node.js:999:3`

**Comment by molant** [comment]
What version of node are you using?

**Comment by wmelton** [comment]
v5.4.1 - so a little old but not hugely outdated?

**Comment by austinkelleher** [comment]
@wmelton Async/await isn't supported until Node.js 7.10.0, and Sonar currently only supports Node 8+.

**Comment by wmelton** [comment]
Interesting with 6.11 being the recommended version for most Mac users though.
![image](https://user-images.githubusercontent.com/1544125/27443220-5d4bfd56-5740-11e7-80f5-618fc73c44cd.png)

**Comment by molant** [comment]
The new LTS is coming in the next few weeks AFAIK.
@alrra was thinking on ways of supporting older versions but haven't had the time to do that yet.
Mind opening an issue asking for support for older versions? If more people request it it will help us with the priorities.

Thanks!
