### ISSUE TITLE
Axe rule doesn't work if sonar is installed globally

### ISSUE THREAD

**Issue by t-sauer** [sonarwhal/sonar#301]
When sonar is installed globally, the axe rule doesn't work:

```
Downloading https://glimmerjs.com/api/assets/manifest.json{ Error: ENOENT: no such file or directory, open '/Users/ts02/Code/glimmer-api-docs/node_modules/axe-core/axe.js'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/ts02/Code/glimmer-api-docs/node_modules/axe-core/axe.js' }
```

It looks like the rule tries to lookup the script to inject into the browser based on the current directory: https://github.com/sonarwhal/sonar/blob/master/src/lib/rules/axe/axe.ts#L57

**Comment by molant** [comment]
@qzhou1607 want to do this one?

**Comment by qzhou1607** [comment]
@molant Sure!

**Comment by t-sauer** [comment]
Oh, I already created a PR for it @qzhou1607
