### ISSUE TITLE
Unable to Read --init Questions

### ISSUE THREAD

**Issue by joshvickerson** [sonarwhal/sonar#302]
Using `sonar --init` in a terminal with a dark background makes the questions unreadable because the text is forced to black. Highlighting the line revealed the text, but as you can see in the attached screenshot, this is not ideal.

<img width="510" alt="sonar --init text is unreadable on a black terminal" src="https://user-images.githubusercontent.com/2325487/27443625-b770c914-5741-11e7-92a1-cedeb1a27825.png">

**Comment by molant** [comment]
@joshvickerson what terminal theme and MacOS version are you using?

**Comment by joshvickerson** [comment]
I'm using the Pro theme on macOS 10.12.5

**Comment by molant** [comment]
This is what I see with the same config:
![screen shot 2017-06-22 at 10 14 29 am](https://user-images.githubusercontent.com/606594/27446776-99f601c8-5733-11e7-95dd-edc676229b80.png)

Any other changes that you've done to the theme?
What version of node are you using? It should be 8.x

**Comment by joshvickerson** [comment]
I changed the font in the theme to Source Code Pro Light, and reduced the inactive window opacity but I'm pretty sure those are the only 2 adjustments I've made to the theme. I'm using node 8.1.2.

**Comment by molant** [comment]
This is what I have:
![screen shot 2017-06-22 at 11 40 52 am](https://user-images.githubusercontent.com/606594/27450189-b0a06bf0-573f-11e7-8af6-0abf6d957d7b.png)

:/

**Comment by austinkelleher** [comment]
I've had similar trouble with visibility on iTerm2 with Solarized Dark theme before. Increasing the "minimum contrast" made the issue go away. Not sure if you're using iTerm or if this will help at all though.

**Comment by joshvickerson** [comment]
Just realized I can export my terminal profile. At a quick glance I also have `antialias text` checked. But here's the whole profile to help you test.
[Pro (Modified).terminal.zip](https://github.com/sonarwhal/sonar/files/1098144/Pro.Modified.terminal.zip)

**Comment by alrra** [comment]
> But here's the whole profile to help you test.

Thanks for taking the time to do that!

----

@joshvickerson We are using [`Inquirer.js`](https://github.com/SBoudrias/Inquirer.js) for that part of the code, and with your custom terminal profile I can reproduce this even with [their example](https://github.com/SBoudrias/Inquirer.js/blob/babdfb2beab514164339be3b5ecbce8cbf1180eb/examples/list.js).

Note: I've imported your custom terminal profile, and depending if I had a black background, white background, or the terminal is not focused, I got all sorts of results:

![](https://user-images.githubusercontent.com/1223565/27596627-c779cf38-5b68-11e7-9426-f9b56472b639.gif)

---

If you consider that your custom terminal profile is not the problem, I suggest [opening an issue in the `Inquirer.js` repository](https://github.com/SBoudrias/Inquirer.js/issues/new). In the issue maybe give as an example [`list.js`](https://github.com/SBoudrias/Inquirer.js/blob/babdfb2beab514164339be3b5ecbce8cbf1180eb/examples/list.js), and try to provide as many details as possible. Thanks!

**Comment by alrra** [comment]
> if I had a black background, white background

Just to make it more clear: if I had a black/white background "under" the terminal
