### ISSUE TITLE
Can't install via npm - canvas error

### ISSUE THREAD

**Issue by cfjedimaster** [sonarwhal/sonar#308]
Trying to install on WSL, and I get the following:

/usr/local/bin/sonar -> /usr/local/lib/node_modules/@sonarwhal/sonar/dist/src/bin/sonar.js

> canvas-prebuilt@1.6.0 install /usr/local/lib/node_modules/@sonarwhal/sonar/node_modules/canvas-prebuilt
> node-pre-gyp install

node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@sonarwhal/sonar/node_modules/canvas-prebuilt/canvas/build'
node-pre-gyp ERR! System Linux 4.4.0-43-Microsoft
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/@sonarwhal/sonar/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/@sonarwhal/sonar/node_modules/canvas-prebuilt
node-pre-gyp ERR! node -v v8.1.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@sonarwhal/sonar/node_modules/canvas-prebuilt/canvas/build'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas-prebuilt@1.6.0 install: `node-pre-gyp install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas-prebuilt@1.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ray/.npm/_logs/2017-06-22T18_56_20_056Z-debug.log

**Comment by molant** [comment]
I've opened an issue in [`canvas-prebuilt`](https://github.com/chearon/node-canvas-prebuilt/issues/14). This repros on Mac as well if you try to install just this package globally.

**Comment by jdalton** [comment]
This looks like a common permissions issue. You'll notice that doing `sudo npm i` will resolve it **(don't `sudo npm i`)**. Instead check out [getting-started/fixing-npm-permissions](https://docs.npmjs.com/getting-started/fixing-npm-permissions). For OSX I do [option 2](https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-2-change-npms-default-directory-to-another-directory)

**Comment by alrra** [comment]
@cfjedimaster Please try what @jdalton [suggested](https://github.com/sonarwhal/sonar/issues/308#issuecomment-311237433), and let us know how it goes. Thanks!

**Comment by molant** [comment]
@alrra, we should update the instructions in the user guide. I had the same problem using the WSL.

**Comment by cfjedimaster** [comment]
I was able to get it installed.

**Comment by arkarwmh** [comment]
Thanks @jdalton it works perfectly!
