### ISSUE TITLE
Update `user guide` documentation to include instructions on how to deal with npm install permission issues

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonar#325]
We should update [`Getting started`](https://github.com/sonarwhal/sonar/blob/47ceeea2555a9867554b4cd96d5cb746201035b5/docs/user-guide/index.md#getting-started) to contain contain some information on how to deal with [`npm install` permission issues](https://github.com/sonarwhal/sonar/issues/308#issuecomment-311237433).

---

See also: https://github.com/sonarwhal/sonar/issues/308

**Comment by qzhou1607** [comment]
@alrra @molant Just curious: I don't see `canvas-prebuilt` is used anywhere in the code, why do we have this dependency?

**Comment by alrra** [comment]
>  I don't see canvas-prebuilt is used anywhere in the code

It is [used by `jsdom`](https://github.com/sonarwhal/sonar/commit/ce54bc9473c6ebd434af02f7466419bc9070f397).
