### ISSUE TITLE
sonar init, what are collectors?

### ISSUE THREAD

**Issue by cfjedimaster** [sonarwhal/sonar#326]
Per the docs, I'm running `sonar --init`, and I'm being asked to select a collector. I have a choice of cdp and json. I've got no idea what a collector is, or cdp. I know what json is obviously, but... yeah, no idea. I'm going to select json, but I think there are two things here:

* the quick start should let us know about this prompt and give us some context as to what to pick
* the CLI should maybe add a bit more text?

**Comment by cfjedimaster** [comment]
Oops, not json, jsdom. So yeah, Ill just pick cdp because it's first, but I hate not knowing what I'm doing. :)

**Comment by alrra** [comment]
>  I hate not knowing what I'm doing. :)

Yes, we should improve things that are not obvious. 

> Per the docs

@cfjedimaster What docs did you read exactly? https://sonarwhal.com/docs/user-guide/?

**Comment by cfjedimaster** [comment]
Sorry - just the quick start.

**Comment by alrra** [comment]
> just the quick start. 

Ok, we should improve that.

@cfjedimaster Can you look over https://sonarwhal.com/docs/user-guide/ and let us know if that clarifies things? Thanks!

**Comment by cfjedimaster** [comment]
I believe I grok it a bit now. Maybe the quick start can add a short sentence saying to just accept the defaults and that you can go to X for details on collectors and formatters).

**Comment by patrick-steele-idem** [comment]
Related?: https://github.com/sonarwhal/sonar/issues/286 :)

**Comment by cfjedimaster** [comment]
Yeah - perhaps. I like connector too, but as I've been a sonar user for like 2ms, I'll hold off on voting. ;)

**Comment by alrra** [comment]
> but as I've been a sonar user for like 2ms, I'll hold off on voting. ;)

Quite the opposite, you have a fresh perspective on things, and that helps!

**Comment by cfjedimaster** [comment]
Sure - done. I still haven't been able to use Sonar due to #327 - but hopefully that gets corrected soon.
