### ISSUE TITLE
Add rule to check the usage of `apple-touch-icon`s

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonar#33]
- [x] Check if the `<link>` tag (e.g. `<link rel="apple-touch-icon" href="apple-touch-icon.png">`) is specified

     Note: In the past, people usually just had the `apple-touch-icon` in the root of the site, but that is no longer consider a good practice and can create a lot of issues (see: https://github.com/h5bp/html5-boilerplate/pull/1622).

- [x] Check if a `180×180px` image is not used

- [x] Check if multiple multiple images of different sizes are used   

     Note: Usually iOS devices get upgraded pretty quickly, [most people being on the latest 2 version of the iOS](https://developer.apple.com/support/app-store/), so specifying multiple sizes of the `apple-touch-icon` just adds to the weight of the page, without no real benefit. One `180×180px` `apple-touch-icon` is nowadays enough for all cases, as [Safari will scale it down automatically if needed](https://realfavicongenerator.net/blog/how-ios-scales-the-apple-touch-icon/) (see also: https://github.com/h5bp/html5-boilerplate/issues/1367).

- [ ] Check if the image [has transparent background](https://realfavicongenerator.net/blog/apple-touch-icon-turns-black/)

- [x] Other?

**Comment by CKGrafico** [comment]
Sorry for the reference, different repo!
