### ISSUE TITLE
Decide how the `CHANGELOG.md` file will look like

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonar#345]
We should start updating the `CHANGELOG.md`, and agree on it's form.

----

My proposal is to use the following structure:

#### Breaking changes

* `<list_of_commits>`

#### Bug fixes / Improvements

* `<list_of_commits>`

#### New features

 * `<list_of_commits>`

----

Where `<list_of_commits>` includes items such as: 

 [`<commit_short_sha>`] - `<commit_short_description>` (See: `<issue_number(s)>`).

----

Here is [an example](https://github.com/alrra/browser-logos/blob/09c098833d43a35d95805178f11401fb66153eea/CHANGELOG.md#3600-october-10-2016).

Notes: 
 * As it gets bigger we can split it into multiple files (e.g.: https://github.com/nodejs/node/blob/master/CHANGELOG.md)
 * I want to automate the process of updating the `CHANGELOG.md` file, so we'll need to update a bit how the [commit messages](https://github.com/sonarwhal/sonar/blob/6a2b6e214903e6f57b2a53c54fbba23a013f3e35/.github/CONTRIBUTING.md#commit-messages) look like (will open a PR for it).

---

@sonarwhal/contributors Thought?

**Comment by molant** [comment]
> I want to automate the process of updating the CHANGELOG.md file, so we'll need to update a bit how the commit messages look like (will open a PR for it).

Yes, please!
