### ISSUE TITLE
Automate release process

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonar#346]
We should have an `npm` script (e.g.: `release`) that will:

- [x] Updates the `CHANGELOG.md` (see: #345)
- [x] Tags a new version and updates the [release](https://github.com/sonarwhal/sonar/releases).
- [x] Publishes a new version on `npm`.
- [ ] Other?

**Comment by alrra** [comment]
- [ ] Triggers a site update.

**Comment by molant** [comment]
* [] publishes a tweet with a link to the changelog?

**Comment by alrra** [comment]
> publishes a tweet with a link to the changelog?

The whole point of having the release process more automated is to release often, so I haven't implement that as I don't think it's a good idea to tweet about every single version. 

We could have an option to only tweet about major versions, but yet again, my opinion is that in general we should tweet also about versions that include important changes (e.g.: a new connector was added), plus, tweets should include something unique about the release they are talking about.

**Comment by molant** [comment]
OK, there's always time to add it later.
