### ISSUE TITLE
axe-core not found error

### ISSUE THREAD

**Issue by cfjedimaster** [sonarwhal/sonar#351]
Using WSL, jsdom as collector, running sonar on a site, I get this error right away. It doesn't stop the command from finishing though.

```
| Traversing the DOM{ Error: ENOENT: no such file or directory, open '/home/ray/node_modules/axe-core/axe.js'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/ray/node_modules/axe-core/axe.js' }
```

**Comment by molant** [comment]
Do you have version 0.1.0 installed (sonar --version)
That issue was reported initially in https://github.com/sonarwhal/sonar/issues/301 and fixed.

**Comment by cfjedimaster** [comment]
Ah confirmed - sorry - working with Sonar today on two machines, two shells, and forgot to update int his one. Looks to be a non-issue.
