### ISSUE TITLE
If no .sonarrc file found, propose user to create a new one

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonar#354]
Some user will most probably just install and do `sonar <url>`, and will get the following error: 

```sh
TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:1167:7)
    at Object.exports.load (/Users/alrra/.nvm/versions/node/v8.1.3/lib/node_modules/@sonarwhal/sonar/dist/src/lib/config.js:87:31)
    at Object.exports.execute (/Users/alrra/.nvm/versions/node/v8.1.3/lib/node_modules/@sonarwhal/sonar/dist/src/lib/cli.js:94:27)
    at run (/Users/alrra/.nvm/versions/node/v8.1.3/lib/node_modules/@sonarwhal/sonar/dist/src/bin/sonar.js:28:34)
    at Object.<anonymous> (/Users/alrra/.nvm/versions/node/v8.1.3/lib/node_modules/@sonarwhal/sonar/dist/src/bin/sonar.js:31:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
```

This constitutes a bad user experience, and I think we should change things so that, if no configurations are found, `sonar` will just use it's defaults (+ maybe also print a message, such as: `Configurations not found, using defaults...`).

----

Thoughts @sonarwhal/contributors?

**Comment by alrra** [comment]
Thoughts @sonarwhal/contributors?

**Comment by molant** [comment]
If we are going to do that then we should review which rules are on by default. I'm thinking more specifically about the ssllabs. It takes a long time to run if the site is not cached.
We could turn it off in this case or look for a way to output more information to the user so "Finishing" is not on the screen for 1min.

Another alternative could be to tell the user that no configuration has been found and if they want sonar to create one and scan the site. Then we launch init. That might be easier.

**Comment by alrra** [comment]
>  I'm thinking more specifically about the ssllabs. It takes a long time to run if the site is not cached.

:+1:

> Another alternative could be to tell the user that no configuration has been found and if they want sonar to create one and scan the site. Then we launch init. That might be easier.

That also works for me.

**Comment by qzhou1607** [comment]
Good catch! 👍 
>This constitutes a bad user experience, and I think we should change things so that, if no configurations are found, sonar will just use it's defaults (+ maybe also print a message, such as: Configurations not found, using defaults...).

**Comment by sarvaje** [comment]
>Another alternative could be to tell the user that no configuration has been found and if they want sonar to create one and scan the site. Then we launch init. That might be easier.

👍

**Comment by molant** [comment]
Changed the title to a more accurate one.

**Comment by cxoltero** [comment]
shouldn't it  log ```no .sonarrc file found```. Someone who uses sonar should be used to read docs, that implicit mention having such a file.

**Comment by molant** [comment]
@cxoltero it's all about making the first run experience as easy as possible :)

**Comment by molant** [comment]
@qzhou1607 have you done a PR for this? It is in the review column but I don't see anything related to this.
