### ISSUE TITLE
Add support for HTTPS in testing

### ISSUE THREAD

**Issue by qzhou1607** [sonarwhal/sonar#369]
- [x] Generate self-assigned certificates
- [x] Edit `cdp` and `jsdom` settings to not throw errors/hang when using self-assigned certificates
- [x] Integrate both `http` and `https` options in the server

**Comment by molant** [comment]
> Edit cdp and jsdom settings to not throw errors/hang when using self-assigned certificates

Will this be an option that we will pass when testing and disabled by default?

**Comment by qzhou1607** [comment]
@molant Yes. It's passed in `configs` and enabled in `rule-runner`.
>Will this be an option that we will pass when testing and disabled by default?
