### ISSUE TITLE
Create new repository with Nellie related illustrations?

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonar#378]
@ststimac What do you think about having a repository to collect all the Nellie related illustrations?

**Comment by ststimac** [comment]
that'd be awesome.

**Comment by ststimac** [comment]
Uh yes, I love nellie's photobook!

Sent using OWA for iPhone
________________________________

**Comment by alrra** [comment]
@ststimac Done, https://github.com/sonarwhal/nellie (when with `nellie` for now because otherwise we needed to use something like `nellie-photobook` or `nellie-s-photobook`)

We'll discuss more about it next week.
