### ISSUE TITLE
Scan multiple pages at once by pointing to sitemap

### ISSUE THREAD

**Issue by dstorey** [sonarwhal/sonar#383]
When talking to the a11y tools team they mentioned the requirement of being able to scan multiple pages, such as the entire site for issues.

Sites should ideally include a sitemap.xml (or other format, e.g. see https://support.google.com/webmasters/answer/183668?hl=en) for SEO, so it would be great if a user could just point to that file to be able to scan the entire site, rather than having to manually create a list of URLs. 

We could even auto-detect the sitemaps file if it is mentioned in the robots.txt file and offer to scan that rather than just homepage.

**Comment by molant** [comment]
This should go in the `sonar-tools` repo. Closing in favor of https://github.com/sonarwhal/sonar-tools/issues/6

**Comment by meleyal** [comment]
The above link is broken. Is this feature still planned?

**Comment by alrra** [comment]
> The above link is broken.

@meleyal Yes, that repository wasn't very useful. 

>  Is this feature still planned?

There are no plans for now.

For web pages, the discussion was to keep `webhint` as it is and have other tools gather the URLs, pass them to `webhint`, and aggregate the results. As for local files, we have [`connector-local`](https://github.com/webhintio/hint/tree/master/packages/connector-local) that can be used to watch and check local files.

**Comment by meleyal** [comment]
@alrra thanks for the info. 

> For web pages, the discussion was to keep webhint as it is and have other tools gather the URLs, pass them to webhint, and aggregate the results.

Is there any existing work on this somewhere?

**Comment by alrra** [comment]
> Is there any existing work on this somewhere?

@meleyal Not that I know of.
