### ISSUE TITLE
Fetch the HSTS preload list regularly

### ISSUE THREAD

**Issue by qzhou1607** [sonarwhal/sonar#386]
As discussed in https://github.com/sonarwhal/sonar/pull/370#discussion_r128285950, a cron job or npm package is needed to keep the HSTS preload list updatet to date in the `strict-transport-security` rule.

The list could be found here: https://cs.chromium.org/chromium/src/net/http/transport_security_state_static.json

**Comment by alrra** [comment]
My thinking is: If there isn't yet a `npm` package, we should create a new repository, have an automated setup that fetches the list, and if something changed, releases a new version and publishes it on `npm`. That way we (and others) can consume it more easily.

**Comment by alrra** [comment]
This may not be needed, see: https://github.com/sonarwhal/sonar/pull/370#issuecomment-317063570.
