### ISSUE TITLE
Need to add type definitions to npm package so we can create external rule/connector

### ISSUE THREAD

**Issue by sarvaje** [sonarwhal/sonar#432]
If we try to create an external rule/connector, we don't have the type definitions, so typescript notifies some errors when they are not.

For example, if we try to create a new `Launcher` for a connector, I have to do something like:
`export class NewLauncher exports Launcher`

`Launcher` has a protected property `port`, but if I try to use that property inside `NewLauncher` I get a typescript error `error TS2339: Property 'port' does not exist on type 'NewLauncher'.`

**Comment by molant** [comment]
@sarvaje what are the folders that should be added to the npm package?

**Comment by sarvaje** [comment]
I'm not sure, in packages like `@types/whatever` what they have are files with extension `.d.ts` so maybe is something we need to do manually or something, But I'm not sure.

**Comment by molant** [comment]
I think that just the `.ts` files should be enough in our case, no need for `.d.ts`.
Also we can look into https://github.com/Microsoft/dts-gen to generate a starting point for the ones we need.

**Comment by molant** [comment]
Anything in the `dist` folder will get published. Nothing to do here.
