### ISSUE TITLE
Ask about browserlist when running --init and update default value

### ISSUE THREAD

**Issue by qzhou1607** [sonarwhal/sonar#446]
When `browserlist` in the config file is set as an empty string, the `targetedBrowsers` in the `context` of a rule will output an empty array. According to @alrra currently this output means all browsers are supported. @molant suggested maybe we have a default of latest 2 versions in the browserlist. And also I think we should document the browerlist in more details.

**Comment by alrra** [comment]
> When browserlist in the config file is set as an empty string, 
>
> According to @alrra currently this output means all browsers are supported. 

Yes, my opinion is that, if the user didn't targeted any specific browsers, we should offer full support.

> @molant suggested maybe we have a default of latest 2 versions in the browserlist. 

👍

**Comment by molant** [comment]
@alrra so what is your final opinion? Your 👍 to my opinion confuses me 😵

**Comment by alrra** [comment]
> so what is your final opinion? Your 👍 to my opinion confuses me 😵

Sorry about that. What I meant by 👍 is that I agree with you that we should have/provide as the default in the `.sonarrc` file  `"last 2 versions"`.

**Comment by molant** [comment]
OK, so the plan for now is:

* Have a default `"browserlist: ["last 2 versions"]` in our default json
* Add another question to the `--init` option to ask about browser support
* `browserlist == []` implies that all browsers are targeted

@alrra did I miss something?

**Comment by alrra** [comment]
> did I miss something?

No.

>  browserlist == [] implies that all browsers are targeted

...all browsers that are somewhat still in use.

**Comment by alrra** [comment]
> Have a default "browserlist: ["last 2 versions"] in our default json

Thinking a bit more about it, I think that should actually be `[  '> 1%',  'last 2 versions' ]`.

---

Note:  [`browserlist` default to](https://github.com/ai/browserslist/blob/630c3f8a1513ee263158259b43f5029b494f32fb/index.js#L303-L307): `[  '> 1%',  'last 2 versions',  'Firefox ESR' ]`.

**Comment by molant** [comment]
> Note: browserlist defaults to: [ '> 1%', 'last 2 versions', 'Firefox ESR' ].

Do we have something wrong in our code? If we don't specify anything in our sonarrc we don't get any list at all.

**Comment by qzhou1607** [comment]
@molant I think it is because of the if condition here https://github.com/sonarwhal/sonar/blob/ac7a3c31d333c21bc44cb4e0037453d0a1aa79bf/src/lib/sonar.ts#L99-L101. `browserslist` never runs if `config.browserslist` is not defined.

**Comment by molant** [comment]
I think we should fix this and use `browserlist`'s default behavior if the user doesn't specify anything. 

Rules will not need to define their "default" if no browsers configured and we will only have to update one single place to change if we decide to use something different than `browserlist`'s default.

Also I think that the most common scenario is users leaving that option blank and not wanting to target old versions of IE. We should still ask them running `--init` just in case.

@alrra?

**Comment by alrra** [comment]
> I think we should fix this and use browserlist's default behavior if the user doesn't specify anything.

Agree.

> We should still ask them running --init just in case.

Agree.
