### ISSUE TITLE
Configure `suggestRemoval` correctly when `targetBrowsers` is empty

### ISSUE THREAD

**Issue by qzhou1607** [sonarwhal/sonar#447]
https://github.com/sonarwhal/sonar/blob/ac7a3c31d333c21bc44cb4e0037453d0a1aa79bf/src/lib/rules/highest-available-document-mode/highest-available-document-mode.ts#L162-L164

See #446 for details.

**Comment by molant** [comment]
Once #451 is merged this can be closed as well.
