### ISSUE TITLE
Same issue reported multiple times for the same resource on jsdom

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonar#460]
**URL:** https://capitalone.com
**Connector:** jsdom
**Rule**: no-disallowed-headers

![image](https://user-images.githubusercontent.com/606594/29789644-961354c4-8beb-11e7-8768-40612e5b900a.png)

This doesn't reproduce with `cdp`

**Comment by qzhou1607** [comment]
Update: The `resourceLoader` receives duplicates urls to load, for some reason the five icons in the hidden mobile navigation bar are loaded twice. It looks like an issue in jsdom. @sarvaje suggested having a filter in `resourceLoader` that avoids sending duplicate requests. I will implement that as the solution.
