### ISSUE TITLE
highest-available-document-mode update wording when suggesting replacing meta tag over header

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonar#477]
url: https://summit.microsoftedge.com
connector: jsdom
rule: highest-available-document-mode
browserslist: default

![image](https://user-images.githubusercontent.com/606594/29938119-8bb6bf18-8e3c-11e7-9469-8de0586a17c1.png)

The result is:
```
'x-ua-comaptible' header was not specified
Meta tag is not needed
```

Having both errors is a bit confusing. If the meta tag is not needed then I shouldn't get the report that the header was not specified, right?

**Comment by alrra** [comment]
> Having both errors is a bit confusing. If the meta tag is not needed then I shouldn't get the report that the header was not specified, right?

The idea is that you should use the HTTP header not the meta tag (unless you specifically request that by configuring the rule), so the rule will try to steer you in that direction: remove the meta tag and use the HTTP header.

**Comment by molant** [comment]
But I thought I was having the message "Meta tag is not needed" because of my browser support matrix, not because I should use the header.

**Comment by molant** [comment]
So IE10 is in the list of default browsers because "last 2". After talking with @alrra we agreed the message could be improved. What about:

> 'x-ua-compatible' header is preferred over meta tag

**Comment by molant** [comment]
Also, specifying that I do not want IE10 as a target throws the same error:
![image](https://user-images.githubusercontent.com/606594/29939729-b44dbdfa-8e41-11e7-9b79-04482bc8e68c.png)

**Comment by alrra** [comment]
> Also, specifying that I do not want IE10 as a target throws the same error:

Yes, because the meta tag is not needed if you are not targeting IE 8/9/10.

**Comment by molant** [comment]
What the rule should say is if:

* IE <= 10: `'x-ua-compatible' header is preferred over meta tag` (or something similar) if meta present
* IE > 10: Meta tag is not needed
