### ISSUE TITLE
`jsdom` gets stuck at `traverse::end`

### ISSUE THREAD

**Issue by qzhou1607** [sonarwhal/sonar#485]
connector: jsdom
url: www.facebook.com

This happens when `axe` is activated and is back to normal when `axe` is deactivated. This delay seems to be a extra long time taken in the line below:
https://github.com/sonarwhal/sonar/blob/79b8da5d337ef915fe2895d424872bdd21ef4111/src/lib/connectors/jsdom/jsdom.ts#L467

**Comment by qzhou1607** [comment]
This issue is relevant to https://github.com/sonarwhal/sonar/issues/192. Currently we always have to wait for 60s and `Error executing script ` is always reported in `axe`.

**Comment by molant** [comment]
> if something is wrong with running the script.

Do we know if something is wrong with the script or is it just that it takes too long to execute?

**Comment by molant** [comment]
One option could be to split the execution in multiple batches. Not sure how that would work though.

**Comment by qzhou1607** [comment]
Yes, below is the error I got when I paste the script to the console in www.facebook.com. So it ended up waiting for the 60s timeout in `evaluate` of `jsdom` when running `axe`. Plus the spinner stops spinning during this 60s (shown as `\ Traversing finished`). So from a user's perspective, it looks like it's stuck. Does the timeout in `evaluate` have to be 60s in `jsdom`? Can this waiting time be shorter? @molant @sarvaje
 

![console-error](https://user-images.githubusercontent.com/20218531/30074230-9c157150-9225-11e7-9d80-e903603eeb6f.PNG)

>Do we know if something is wrong with the script or is it just that it takes too long to execute?

**Comment by molant** [comment]
> Does the timeout in evaluate have to be 60s in jsdom? Can this waiting time be shorter?

I think a better solution will be to create another process with just jsdom to inject the JS, maybe one process per JS `evaluate`d so there aren't any conflicts between them. We will have to change the guidance and `evaluate` as soon as it makes sense (`targetfetch::end`?). And also maybe a custom timeout for this type of rules. This should give us better performance and in the worst case the spinner will not be blocked. @sonarwhal/contributors what do you think?

@sarvaje has been working with child process in https://github.com/sonarwhal/online-service so he can probably help you if we decide to go down this road.

**Comment by molant** [comment]
@qzhou1607 the child process will have to have it's own code that only runs jsdom, navigates to that url and then evaluates the script. We should only have to send the script we want to run and then return the result of the execution if it can be serialized (and find a way if it can't be).

@sarvaje can you work with @qzhou1607? This should be somehow similar to what you are doing with the scanner.

**Comment by sarvaje** [comment]
ok
