### ISSUE TITLE
sonar suggests upgrading to a new version after installing that version

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonar#507]
![](https://user-images.githubusercontent.com/1223565/30234196-dac37514-94af-11e7-97bc-c8f3863194d4.png)

**Comment by qzhou1607** [comment]
@alrra Did it still happend when you run it the second time? It always needs the first time to brush up the persisted result. See https://www.npmjs.com/package/update-notifier#how.

**Comment by alrra** [comment]
> Did it still happend when you run it the second time? 

No.

---

Closing, as I didn't see this happening anymore.

**Comment by alrra** [comment]
I got this again. :(

**Comment by molant** [comment]
The data gets updated every hour or so. Will be great to find a way to force it somehow.
