### ISSUE TITLE
Add integration with retire.js

### ISSUE THREAD

**Issue by aaronpowell** [sonarwhal/sonar#514]
[Retire.js](http://retirejs.github.io/retire.js/) is a tool for doing vulnerability scanning of JavaScript libraries and reporting issues when they are detected.

At the moment this is uses as an external tool that you can use from a CLI, browser plugin or other ways, but given it's just a Node.js module I think there would be value in hooking it into Sonar so that they can be reported in a single report.

**Comment by molant** [comment]
From what I've read in the documentation it looks retire.js info comes from [a json that it is manually maintained in the repo](https://github.com/RetireJS/retire.js/blob/master/docs/blogpost.md#the-source) and the last time it was updated was about a month ago.

At the moment we are using [snyk.io vulnerability db](https://snyk.io/vuln/). One of the cool things about is that it gets updated very frequently (almost daily). sonar automatically updates the local data if it it's older than 24h (and we [update the shipped data on each release](https://github.com/sonarwhal/sonar/blob/b2e30d6d1fd0f0a3f00a80fd04420d662ca6747a/scripts/release.ts#L303)).

What would be the benefits of using this package over our current implementation in [no-vulnerable-javascript-libraries](https://sonarwhal.com/docs/user-guide/rules/no-vulnerable-javascript-libraries.html).

Thanks!

**Comment by aaronpowell** [comment]
Well I didn't know that snyk exists. Looks like it does all that we'd need for it to do.
