### ISSUE TITLE
.sonarrc file doesn't get created viar `sonar https://website.com`

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonar#562]
Please tell us about your:

## Environment

* __`sonar` version:__ 0.10.0
* __`Node.js` version:__ 8.5.0
* __`npm` version:__ 5.4.2

## Error

Try running `sonar https://sonarwhal.com` (or any other site) in a folder where there isn't a config file. It will prompt you if you want to create a new config file. Pressing yes will prompt you again, and again.

**Comment by qzhou1607** [comment]
This seems still happening. The json validator  just doesn't let `.sonarrc` pass even when it's valid, but removing `formatter` from `.sonarrc` let it pass.

**Comment by molant** [comment]
Are you using the latest version and are you sure your `.sonarrc` file has `formatters` instead of `formatter` (and that property is an Array)?

**Comment by molant** [comment]
I can't repro this with sonar 0.10.1.
This seems like a different issue. Can you open a new issue and give more details (are you using the module, from the source, is there another `.sonarrc` file in there?)

**Comment by qzhou1607** [comment]
@molant For some reason in my machine the `config-schema` loaded by `require.js` in `is-my-json-valid` uses `formatter` instead of `formatters`. It was fixed after running another build. Thanks!
