### ISSUE TITLE
Recommend `text/javascript` as the media type for JavaScript resources

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonar#568]
> Servers should use `text/javascript` for JavaScript resources. Servers should not use other JavaScript MIME types for JavaScript resources, and must not use non-JavaScript MIME types.

Ref: 
 
  * https://github.com/whatwg/html/pull/3096
  * https://github.com/bmeck/I-D/issues/2

**Comment by gemal** [comment]
I dont think this change is correct

https://www.iana.org/assignments/media-types/application/javascript = OBSOLETE
https://www.iana.org/assignments/media-types/text/javascript = COMMON

**Comment by alrra** [comment]
@gemal Historically, `text/javascript` was recommended and used since the early days, so chances of it breaking things is less then the recently IANA recommended `application/javascript`. The [HTML spec](https://github.com/whatwg/html/pull/3096) was also updated and recommends using `text/javascript` (and usually the spec tries to reflect the reality, not some ideal world).

---

Note: For current user agents it shouldn't matter that much which of the two you use, but with this project we try to recommend what is usually considered the best option.

Hope that clarifies things.

**Comment by alrra** [comment]
>  This document updates the existing media types for the ECMAScript programming language.  It supersedes the media types registrations in [RFC4329] for "application/javascript" and "text/javascript".

From https://tools.ietf.org/html/draft-ietf-dispatch-javascript-mjs-00

**Comment by maple3142** [comment]
[https://www.rfc-editor.org/rfc/rfc4329.txt](https://www.rfc-editor.org/rfc/rfc4329.txt)
But this said text/javascript is obsolete

**Comment by alrra** [comment]
@maple3142 Please read the previous comments. Thanks!

**Comment by alrra** [comment]
See also: https://github.com/whatwg/mimesniff/issues/76.
