### ISSUE TITLE
Label issues for new contributors 

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonar#586]
GitHub kinda hints on this:

![](https://user-images.githubusercontent.com/1223565/31733645-f6cfd41e-b444-11e7-9c5c-5691ca586375.png)

\+ there is also [Hacktoberfest](https://hacktoberfest.digitalocean.com/)!

**Comment by molant** [comment]
I've added a few ones. From now on we should start labelling as soon as we create them.
