### ISSUE TITLE
Unexpected Token at <

### ISSUE THREAD

**Issue by grantkemp** [sonarwhal/sonar#598]
I was unable to see the output of the following test: 
https://sonarwhal.com/scanner/bcd43ac0-963f-4920-b831-7287cbb7a866

It displays: 
Unexpected token < in JSON at position 0

I would have expected to see the results

**Comment by molant** [comment]
Can you please open this in https://github.com/sonarwhal/sonarwhal.com?
It's related to the site. If you refresh you'll get eventually the results. It has happened to a few people today (including myself).

@sarvaje @qzhou1607 can you please take a look?

**Comment by qzhou1607** [comment]
@molant @sarvaje I don't see the error. Was it fixed?

**Comment by molant** [comment]
It happens randomly. We should check that whatever we receive from the dB is a json and if not request it again.

**Comment by qzhou1607** [comment]
Follow up in https://github.com/sonarwhal/sonarwhal.com/issues/270
