### ISSUE TITLE
EACCES: permission denied with canvas-prebuilt during installation

### ISSUE THREAD

**Issue by gbiagomba** [sonarwhal/sonar#600]
Hello,

I tried installing sonar and it did not work. I keep getting an error whenever I try to install it. Below is the OS, package versions and error output. 
 

**OS:** 
- Kali Linux 2.0

**Package version**
- Node 8.8.1
- NodeJS 4.8.4
- npm 5.5.1
- npx 9.6.0

**Error Output:**
```
root@kali:/opt/sonar# npm install -g --engine-strict @sonarwhal/sonar
/usr/local/bin/sonar -> /usr/local/lib/node_modules/@sonarwhal/sonar/dist/src/bin/sonar.js

> canvas-prebuilt@1.6.0 install /usr/local/lib/node_modules/@sonarwhal/sonar/node_modules/canvas-prebuilt
> node-pre-gyp install

node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@sonarwhal/sonar/node_modules/canvas-prebuilt/canvas/build'
node-pre-gyp ERR! System Linux 4.9.0-kali4-amd64
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/@sonarwhal/sonar/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/@sonarwhal/sonar/node_modules/canvas-prebuilt
node-pre-gyp ERR! node -v v8.8.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp ERR! not ok 
EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@sonarwhal/sonar/node_modules/canvas-prebuilt/canvas/build'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas-prebuilt@1.6.0 install: `node-pre-gyp install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas-prebuilt@1.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-10-26T18_57_03_883Z-debug.log
```

![image](https://user-images.githubusercontent.com/5851606/32071748-34c14b9e-ba5e-11e7-9cb4-9f9f350a0b33.png)

**Comment by qzhou1607** [comment]
@gbiagomba You can find more information about the permission issue [here](https://sonarwhal.com/docs/user-guide/index.html#permissionissue)

**Comment by molant** [comment]
That does look like the permission issue @qzhou1607 mentions. Can you give it a try with the `npx` command?

```bash
npx @sonarwhal/sonar https://website.com
```

**Comment by molant** [comment]
@gbiagomba There's also @jdalton's comment on https://github.com/sonarwhal/sonar/issues/308#issuecomment-311237433
Check https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by fdellwing** [comment]
Using the following command fixxed the error for me: `sudo npm install -g --engine-strict @sonarwhal/sonar --unsafe-perm=true`

**Comment by petermbenjamin** [comment]
I am also receiving this error, but my use-case is slightly different (e.g. docker container).
<img width="1077" alt="screen shot 2017-10-28 at 11 09 49 pm" src="https://user-images.githubusercontent.com/6811830/32141123-4614fe8a-bc35-11e7-8bc2-f72357543722.png">

I have tried following @qzhou1607's suggestion, but that didn't help.
<img width="1121" alt="screen shot 2017-10-28 at 11 10 22 pm" src="https://user-images.githubusercontent.com/6811830/32141126-6bd6be2e-bc35-11e7-9c19-31b7b5ff1a0f.png">

I have also tried following @molant's suggestion, but that didn't help either.
<img width="1072" alt="screen shot 2017-10-28 at 11 14 28 pm" src="https://user-images.githubusercontent.com/6811830/32141147-e16aa696-bc35-11e7-9d70-cfe3bc0e6311.png">

**Comment by fdellwing** [comment]
@petermbenjamin Why did you not try my suggestion? It's from the official npm github and works like a charm...

**Comment by molant** [comment]
@petermbenjamin creating a new `npm-global` folder will not work if you do it under `/root/`. Try creating a new user or in a different folder outside `/root/` see if that changes. I had no problems with the new user option.

**Comment by gbiagomba** [comment]
@fdellwing you sir are the bumb, you suggestion worked!
@molant thank you for trying, but the gentleman above ( fdellwing) suggestion seemed to have done the trick
