### ISSUE TITLE
aXe rules appear to be flagging color contrasts at exactly 4.5:1

### ISSUE THREAD

**Issue by melanierichards** [sonarwhal/sonar#602]
WCAG 2.0, Level AA [requires a 4.5:1 color contrast ratio](https://www.w3.org/TR/WCAG20/#visual-audio-contrast), but the scanner rules seem to be flagging ratios at exactly 4.5:1. Example: foreground of #fff, background of #0078d7.

**Comment by molant** [comment]
@melanierichards can you provide more details?
Will need at least a URL where this does reproduce before opening an issue on https://github.com/dequelabs/axe-core

**Comment by molant** [comment]
Also could be related to https://github.com/dequelabs/axe-core/issues/589#issuecomment-339969707 but we are using the latest 2.4.2 🤔

**Comment by marcysutton** [comment]
Definitely need more details for that one. I adjusted the ratio a while back to round down instead of up at 4.49:1 so it wouldn't flag those, so something else must be going on if it's the current version.

**Comment by molant** [comment]
@marcysutton I'll work with @melanierichards and open an issue once we have the a reduction.

Thanks!

**Comment by melanierichards** [comment]
Sorry, didn't realize URL would be needed if hex codes were provided. It's on https://developer.microsoft.com/en-us/microsoft-edge/, basically any of those links in the tools section, as well as the buttons with white text on blue. It was also being flagged when I scanned directly with the aXe tool in Chrome.

The WebAIM color contrast checker is flagging it too, yet expressly acknowledging the ratio is 4.5:1, which is supposed to pass WCAG AA. https://webaim.org/resources/contrastchecker/?fcolor=0078D7&bcolor=FFFFFF. I don't know if they're running off the same stuff so that is to be expected, but it is interesting.

**Comment by marcysutton** [comment]
aXe is showing it as 4.49:1, which technically doesn't pass. See https://github.com/dequelabs/axe-core/issues/494 for more information.

**Comment by melanierichards** [comment]
Hmm, then these other tools must be rounding up, hence the confusion.
