### ISSUE TITLE
Does the sonar app send any data to a remote server ?

### ISSUE THREAD

**Issue by simlevesque** [sonarwhal/sonar#606]
Hi,

I'd like to know if you ping home before using it on sensitive websites.

**Comment by molant** [comment]
Hi @simlevesque,

sonar when used from the CLI doesn't ping home, in the online version it stores the results of the scan. One thing to keep in mind is that there are rules that integrate with third party services. Depending on your configuration it might send data to their servers to obtain results. Some examples of rules that do so:

* html-checker will send the HTML of the page to https://html5.validator.nu/
* image-optimization-cloudinary will upload the images to your Cloudinary account (if you have configured one)
* ssllabs will try to analyze the url you've passed sonar using the API for https://www.ssllabs.com/ssltest/ 

The documentation of the rules should indicate when there is a communication with a third party service. If you find out one that doesn't report it, we should update it.

Hope that helps!
