### ISSUE TITLE
Incorrect suggestion for JS content type

### ISSUE THREAD

**Issue by michaelmior** [sonarwhal/sonar#607]
Using the Sonar web interface, I'm told that I should use `text/javascript` instead of `application/javascript`. However, according to [RFC 4329](https://www.ietf.org/rfc/rfc4329.txt), `text/javascript` is obsolete.

**Comment by alrra** [comment]
@michaelmior See #568.

**Comment by michaelmior** [comment]
@alrra Thanks for the pointer!
