### ISSUE TITLE
Links to documentation are all dead

### ISSUE THREAD

**Issue by aubertc** [sonarwhal/sonar#608]
Are you aware that every single link to the documentation is dead?
For every single "Errors & Warnings" for which there is an error, the "documentation" button points to a 404 page?

**Comment by alrra** [comment]
@aubertc Sorry about that, we recently [made some changes](https://github.com/sonarwhal/sonarwhal.com/pull/269) and an issue slipped in.

**Comment by alrra** [comment]
@aubertc Thanks for opening this issue, we sincerely appreciate it! 💜 

Things should be fixed now.

---

@qzhou1607 When you have time, can you check that we haven't missed anything else? Thanks!
