### ISSUE TITLE
[docs] Issue with 'User guide'

### ISSUE THREAD

**Issue by ostyuchenko** [sonarwhal/sonar#614]
Please tell us about your:

## Environment

* __`sonar` version:__
* __`Node.js` version:__
* __`npm` version:__

## `sonar` configuration

<details>
<summary>sonar's configuration</summary>

```js



```

</details>

## URL for which `sonar` failed

* __URL:__

## Output

Please include the raw output generated by `sonar`, or if possible,
the raw output from running `sonar` in debug mode: `sonar --debug <URL>`.

<details>
<summary>sonar's raw output</summary>

```text



```

</details>

**Comment by alrra** [comment]
@ostyuchenko Can you provide more information? What exactly is the issue? Thanks!

**Comment by alrra** [comment]
Closing until further details are provided.
