### ISSUE TITLE
`axe` rule is not using the property `rulesTimeout`

### ISSUE THREAD

**Issue by sarvaje** [sonarwhal/sonar#630]
The rule `axe` is calling always to `evaluate` with one argument, so it is using the default value `60000` instead of the value in `rulesTimeout`.

https://github.com/sonarwhal/sonar/blob/master/src/lib/connectors/jsdom/jsdom.ts#L514

**Comment by molant** [comment]
Can we change the timeout in the online version just for this rule?

**Comment by molant** [comment]
Talked with @sarvaje about timeouts. The plan to try to improve the success on axe in the online-scanner is:

* Fix this issue
* Increase the timeout for this particular error to something bigger than the current time (will have to do some tests)
* Increase the `maxRunTimeout` of the job so it isn't marked as error by mistake. This will have an impact on how long the messages are blocked but that should be all.

**Comment by sarvaje** [comment]
@molant `maxRunTimeout` will also impact on how long a "worker" is blocked.

**Comment by molant** [comment]
Yes, but hopefully that will only block the workers that are running long tasks like `axe` 😊

In any case, we should look at the queues once the changes are deployed.

**Comment by sarvaje** [comment]
Yes, just those workers :)
