### ISSUE TITLE
Possible new rule: HPKP deprecated in Chrome 67

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonar#631]
>Deprecate support for public key pinning (PKP) in Chrome, and then remove it entirely.

> This will first remove support for HTTP-based PKP (“dynamic pins”), in which the user-agent learns of pin-sets for hosts by HTTP headers. We would like to do this in Chrome 67, which is estimated to be released to Stable on 29 May 2018. 

More info in https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/he9tr7p3rZ8/eNMwKPmUBAAJ

**Comment by alrra** [comment]
> Possible new rule: HPKP 

Or maybe just update the [`no-disallowed-headers`](https://sonarwhal.com/docs/user-guide/rules/no-disallowed-headers/#page-heading) rule?

**Comment by molant** [comment]
We'll have to update about the documentation and point to the different documents that explain why for each header (or at least this one).

**Comment by alrra** [comment]
> We'll have to update about the documentation and point to the different documents that explain why for each header (or at least this one).

Yes, I was referring to the whole thing, docs, and code.

I was just curious if other people agree that we should have another rule just for this header.
