### ISSUE TITLE
Add rule to avoid HTTP redirects

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonar#641]
This is part of https://github.com/sonarwhal/sonar/issues/438 and more specifically https://github.com/sonarwhal/sonar/issues/438#issuecomment-342939073

> I'm starting with this rule (at least the basic redirects). These are my initial thoughts:
>
>* Allow the user to configure the number of hops, by default 0
>* Try to add information about time spent on dns lookup, redirects, etc. I believe we've already added that information to `request` and it might be a good opportunity to get @axemclion work on #420 merged somehow. This part of the rule's should be conditional, some connectors might not have it (like the edge15 one)
>
>**Main question**: What do we do about the main page? Some websites have friendly urls. E.g.: https://edge.ms --> https://developer.Microsoft.com/en-us/microsoft-edge/
I think we should add another property for the number of hops for the `sourceTarget` that will be 0 by default in the CLI but maybe 1-2 in the online-scanner.

**Comment by alrra** [comment]
> >**Main question**: What do we do about the main page? Some websites have friendly urls. E.g.: https://edge.ms --> https://developer.Microsoft.com/en-us/microsoft-edge/
I think we should add another property for the number of hops for the `sourceTarget` that will be 0 by default in the CLI but maybe 1-2 in the online-scanner.

Personally, in that example, I don't see https://edge.ms as the "main" page, just as an alternative (short) URL. 

Maybe allow URL/pattern related configs, as we do with [`ignoredUrls`](https://sonarwhal.com/docs/user-guide/#ignoringdomains)?

**Comment by molant** [comment]
>  I don't see https://edge.ms as the "main" page

Then what about https://dev.microsoftedge.com ? 
That's the url used everywhere. It is still going to redirect to the long one.

> Maybe allow URL/pattern related configs

How would that work? I still prefer having separate redirect options for target and resource but happy to explore other options..

**Comment by alrra** [comment]
> Then what about https://dev.microsoftedge.com ?

I see it the same as with https://edge.ms , it's a shorter version of the final URL.

An example were I personally don't see it like that is:

https://www.microsoft.com/ => https://www.microsoft.com/en-us/  or https://www.microsoft.com/ro/

> How would that work?

Same as for [other rules](https://sonarwhal.com/docs/user-guide/rules/content-type/#cantherulebeconfigured).

```json
"no-http-redirects": [ "warning", {  
   ".*\\.js": 3
}]
```
