### ISSUE TITLE
[docs] Issue with 'Image optimization with Cloudinary' documentation page

### ISSUE THREAD

**Issue by zverolen** [sonarwhal/sonar#646]
https://sonarwhal.com/docs/user-guide/rules/image-optimization-cloudinary/index.html
It seems that the example snippets have the wrong rule name:
`"image-optimization-cloudinary"` instead of `"cloudinary"`, e.g.
```
"cloudinary": ["error", {
    "apiKey": "your api key",
    "apiSecret": "your api secret",
    "cloudName": "your cloud name",
}]
```

**Comment by alrra** [comment]
Thanks, @zverolen!
