### ISSUE TITLE
[docs] Issue with 'Accessibility assesment with aXe'

### ISSUE THREAD

**Issue by jasonday** [sonarwhal/sonar#650]
https://sonarwhal.com/docs/user-guide/rules/axe.html

Documentation on axe reporting levels for .sonarrc:

```
"rules": {
        "amp-validator": "off",
        "apple-touch-icons": "error",
        "axe": "error",  //what are the available options?
```

**Comment by alrra** [comment]
>  // what are the available options?

@jasonday See: 

* https://sonarwhal.com/docs/user-guide/#rules
* https://sonarwhal.com/docs/user-guide/rules/axe/#cantherulebeconfigured
